### PR TITLE
Initial attempt to support Windows

### LINKED ISSUE #43: Support for Windows
# Why we should support Windows

... and other operating systems
## The accademic argument

We met with a couple professors from Quinnipiac University. They wanted to take a closer look at MouseTrap and possibly integrate it into their curriculum. Great! The dialog went something like this (this is a dramatized reinactment; the names have been changed to protect the innocent):

Alice: What language is it in?
Bob: Python.
Alice: Oh. We use Java. OK, well maybe that's not so bad. Let's install it.
Bob: OK, boot into Linux.
Alice: Oh, I need Linux? Hmm... OK, I'll install Fedora into VirtualBox.
Bob: Nope, that won't work. VirtualBox doesn't support the webcam very well. How about dual booting?
Alice: Ugh... OK, I guess so. But that means I'll have to ask my students to dual boot too?! Maybe this isn't such a good idea.

So, if we want more accademics to use MouseTrap in their curricula, which would mean that more students get exposed to MouseTrap, we need to make it easier to get involved. And that means making it easier to install and get up and running. Asking them to dual boot to try out a simple application is asking too much. We need to allow students and faculty to install, run, and develop in environments of their choosing.
## The humanitarian argument

MouseTrap should not restrict who it helps based on the operating system they choose.
# First effort

I was able to get MouseTrap to "compile" and run under windows. I've created a `windows` branch with the changes I had to make and instructions in `README.windows.md`.
# Issues
- I had to disable i18n. That should be fixed.
- I did not try installing MouseTrap. I just ran it in-place (`make run`). I doubt the install would succeed since python is installed in a much different place in Windows (`C:\Python27`).
- I did not run the tests yet (`make check` nor `make distcheck`). I suspect they will pass.
# Questions
- Do we agree that this is a worthy effort?
- Should it exist as a variation on a separate branch? Or should it be merged and maintained in the main line? If it is separate, how do we handle changes? If it is merged, testing may become more difficult, documentation more confusing (as installation may be different).
- What about other operating systems? OS X? Other flavors of Linux?

### PR DESCRIPTION
**Pull request by StoneyJackson**
Asking interested students or faculty to natively install Fedora or Ubuntu
is a tall order. Plus it would be nice to reach a wider audience.

I got this working under Windows 8 on a Lenova Yoga laptop.  Prerequisites
and instructions are in README.windows.md.

To make it work, I had to make the following changes:
- Disabled gettext. For whatever reason, it could not find the
  .mo file. It was generated correctly, and it existed (programmatically
  checked in i18n.py) but gettext still claimed it couldn't find it.
- Downgraded version numbers for automake and autoconf. We might want to
  downgrade these in the mainline too.
- Removed USE_COMMON_DOC_BUILD flag in autogen.sh which is checked in
  gnome-autogen.sh. This was triggering gnome-autogen.sh to check for a
  full gnome-common enviornment, which I don't have under Windows.
  Turns out that USE_COMMON_DOC_BUILD is obsolete anyway
  (https://bugzilla.gnome.org/show_bug.cgi?id=729931). It should be
  removed in the mainline too.
- Added gnome-autogen.sh. This ships with the gnome-common package. I
  couldn't find an easy way to install gnome-common under windows. So, I
  decided to distribute it. Other ideas?
- Changed default camera index from -1 to 0. For some reason -1 crashes
  mousetrap on Windows. Unless we have a known, verified usecase for -1,
  we should probably change this to 0 in the mainline too (assuming it
  works Linux too).

Closes #43

### CODE REVIEW

**Comment by StoneyJackson** [comment]
Don't merge yet. Needs work.

**Comment by StoneyJackson** [comment]
Need to address gettext on Windows.

https://bazaar.launchpad.net/~bialix/gettext-py-windows/trunk/view/head:/gettext_windows.py

**Comment by StoneyJackson** [comment]
More information in issue #43

**Comment by kevin-brown** [comment]
I was able to get MouseTrap installed on Windows 7 today and wrote up a more detailed install guide.

https://gist.github.com/kevin-brown/bcea8ac4aacd797b792b#file-installing-md

Because I was running under VirtualBox, I was not able to fully test the program (forgot to redirect the webcam).  But it did install correctly using `pip install .` and it set up the script in the correct directory. The script did run (with a few tweaks which were committed), but it errored out when the camera could not be found, and I ran out of time.

The next time I test, I'll be gathering the development requirements and I'll test the `make` targets.

**Comment by kevin-brown** [comment]
I'm going to close out this pull request and create a new one with it pointing at `gnome3-wip` instead of the refactoring branch.

**Pull request closed without merging**
